Document: lsyncd
Title: Debian lsyncd Manual
Author: <insert document author here>
Abstract: This manual describes what lsyncd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/lsyncd/lsyncd.sgml.gz

Format: postscript
Files: /usr/share/doc/lsyncd/lsyncd.ps.gz

Format: text
Files: /usr/share/doc/lsyncd/lsyncd.text.gz

Format: HTML
Index: /usr/share/doc/lsyncd/html/index.html
Files: /usr/share/doc/lsyncd/html/*.html
